// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'saludo_api_service_test.dart' as saludo_api_service_test;
import 'saludo_bloc_test.dart' as saludo_bloc_test;

void main() {
  saludo_api_service_test.main();
  saludo_bloc_test.main();
}
